stages:
  - build
  - test
  - cleanup

.template_ubuntu: &ubuntu
  tags:
    - linux
    - avx2

cleanup:
  <<: *ubuntu
  stage: cleanup
  when: always
  script:
    - pip3 uninstall -y ngsgui

build:
  <<: *ubuntu
  stage: build
  script:
    - pip3 install --user .

test:
  <<: *ubuntu
  stage: test
  before_script:
    - export NETGENDIR=/opt/netgen_gitlab_runner/bin
    - export PYTHONPATH=$NETGENDIR/../lib/python3.7/site-packages/:$PYTHONPATH
    - export PATH=$NETGENDIR:$PATH
    - export LD_LIBRARY_PATH=$NETGENDIR/../lib:$LD_LIBRARY_PATH
  script:
    - cd test && python3 -m pytest
  artifacts:
    paths:
      - test/images/*
    expire_in: 1 week
